language:
  - python
python:
  - "3.8"
stages:
- PR checks ✅
install:
  - make requirements-local.py
jobs:
  include:
  - stage: PR checks ✅
    env:
    - NAME=Validation Checks
    script: make lint.py
